### ISSUE TITLE
Input File

### ISSUE THREAD

**Issue by jmskoh** [SteenOmicsLab/multiFLEX-LF#1]
Hi there, I tested the GUI using the test data and it worked fine.
But when I ran it using my data file, it didn't work. 
I had the row titles exactly the same as the test file, just wondering if the entries need to be in a specific format? 
Thanks!

**Comment by PHiort** [comment]
Hi there, 
the issue should be fixed in the new release: https://github.com/SteenOmicsLab/multiFLEX-LF/releases/tag/v1.1.0
Thanks!
